# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkstatus" do
  version "0.1.2"

  on_macos do
    on_intel do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_darwin_amd64.tar.gz"
      sha256 "3a34bee5a1cd33affca76bfb08f67dd6888532a3dad2239d6ae58bb435a3da1c"
    end
    on_arm do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_darwin_arm64.tar.gz"
      sha256 "249662a9ad86bbbb965f65ede7efdbc93cfb2cde88f6c647309399c8085baaaf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_linux_amd64.tar.gz"
      sha256 "4208ac60d5a02451cfc47282f57c561338db0dc81107a1b67361c4b4aaec864e"
    end
    on_arm do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_linux_arm64.tar.gz"
      sha256 "6d14349cba7148018617d5f934b76566f8d7d8cf218dfc9f21bf6d4e0290b104"
    end
  end

  name "linkstatus"
  desc "Internet connection monitor — TUI dashboard, background monitor, desktop notifications"
  homepage "https://github.com/BestDevSpace/linkstatus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkstatus"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/linkstatus"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This binary is not Apple-notarized. If macOS still blocks it, open
    System Settings → Privacy & Security and choose Open Anyway, or run:
      xattr -dr com.apple.quarantine "$(command -v linkstatus)"
  EOS
end
