# This file was generated by GoReleaser. DO NOT EDIT.
cask "linkstatus" do
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_darwin_amd64.tar.gz"
      sha256 "b6ca5b84b3f98a4bbe9947c64b706401c7d7322f12f6875cfe30939f80bcc404"
    end
    on_arm do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_darwin_arm64.tar.gz"
      sha256 "d42e5b294f991ebe18600eb0e76babc8a9837db365887054db56895980bec1a4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_linux_amd64.tar.gz"
      sha256 "8324cc703b2ea1a6b1aabab0d0bf4e5597af845d84358573238a59ef39e0de0b"
    end
    on_arm do
      url "https://github.com/BestDevSpace/linkstatus/releases/download/v#{version}/linkstatus_#{version}_linux_arm64.tar.gz"
      sha256 "b7e6ab294730cb7915f0146f1503be1416e9b6b1726e8ffcb1f546e2e4ea5760"
    end
  end

  name "linkstatus"
  desc "Internet connection monitor — TUI dashboard, background monitor, desktop notifications"
  homepage "https://github.com/BestDevSpace/linkstatus"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "linkstatus"

  # No zap stanza required

end
